const DEFAULT_IMAGE_RATIO = 1;
const DEFAULT_GRID_SPACING = 4;
const DEFAULT_NUM_COLUMNS = 3;
const DEFAULT_ANIMATION_DURATION = 250;

export {
  DEFAULT_IMAGE_RATIO,
  DEFAULT_GRID_SPACING,
  DEFAULT_NUM_COLUMNS,
  DEFAULT_ANIMATION_DURATION,
};
